yarp connect /icub_kovan/head_motor_calculator/obj1_head_motor_command /icub_kovan/action_selector/obj1_head_motor_command;
yarp connect /icub_kovan/head_motor_calculator/obj2_head_motor_command /icub_kovan/action_selector/obj2_head_motor_command;
yarp connect /icub_kovan/head_motor_calculator/obj3_head_motor_command /icub_kovan/action_selector/obj3_head_motor_command;
yarp connect /icub_kovan/head_motor_calculator/gaze1_head_motor_command /icub_kovan/action_selector/gaze1_head_motor_command;
yarp connect /icub_kovan/head_motor_calculator/gaze2_head_motor_command /icub_kovan/action_selector/gaze2_head_motor_command;
yarp connect /icub_kovan/head_motor_calculator/human_head_motor_command /icub_kovan/action_selector/human_head_motor_command;
yarp connect /icub_kovan/head_motor_calculator/hand_head_motor_command /icub_kovan/action_selector/hand_head_motor_command;
